spring:
  config:
    import: optional:classpath:application-secret.yml

  # Docker MySQL 연결 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/urecadb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul

  # Local Redis 설정
  data:
    redis:
      host: localhost
      port: 6379

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true